services:
  m6-epg:
    image: ghcr.io/lucforcier/m6-epg:latest
    build:
      context: .
      network: host
    network_mode: host
    environment:
      DB_PATH: ${DB_PATH:-/data/m6.db}
      GUIDE_PATH: ${GUIDE_PATH:-/data/m6.xmltv}
      COVERAGE_DAYS: ${COVERAGE_DAYS:-21}
      M6_LOCATION: ${M6_LOCATION:-Europe/Paris}
      OUTPUT_LOCATION: ${OUTPUT_LOCATION:-America/Toronto}
      HTTP_ADDR: ${HTTP_ADDR:-0.0.0.0:8080}
      REFRESH_TIME: ${REFRESH_TIME:-03:00}
      SCHEDULE_LOCATION: ${SCHEDULE_LOCATION:-America/Toronto}
    volumes:
      - m6-data:/data
    restart: unless-stopped

volumes:
  m6-data:
