services:
  m6-epg:
    image: ghcr.io/lucforcier/m6-epg:latest
    ports:
      - "18083:8080"
    environment:
      TZ: America/Toronto
      REFRESH_TIME: "03:00"
      SCHEDULE_LOCATION: America/Toronto
    volumes:
      - /raid/portainer/iptv/m6-epg:/data
    restart: unless-stopped
